---
- name: wait for connection
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 300

- name: apt update
  ansible.builtin.apt:
    update_cache: true
    lock_timeout: 120

- name: set hostname
  copy:
    content: "{{ name }}"
    dest: /etc/hostname
  notify: reboot
